// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { products } from "../services/database";
import { useCart } from "../context/CartContext";
import Newsletter from "../components/Newsletter";

const ProductDetail = () => {
  const { id } = useParams();
  const { addToCart } = useCart();
  const [quantity, setQuantity] = useState(1);
  const [activeTab, setActiveTab] = useState("description");
  const [selectedImage, setSelectedImage] = useState(0);

  // Bootstrap Alert State
  const [showAlert, setShowAlert] = useState(false);
  const [alertMsg, setAlertMsg] = useState("");

  const product = products.find((p) => p.id === parseInt(id));

  if (!product) {
    return (
      <div className="container py-5">
        <div className="text-center">
          <h2>Product not found</h2>
          <Link to="/shop" className="btn btn-primary">
            Back to Shop
          </Link>
        </div>
      </div>
    );
  }

  const handleAddToCart = () => {
    for (let i = 0; i < quantity; i++) {
      addToCart(product);
    }
    setAlertMsg(`${quantity} ${product.name}(s) added to cart!`);
    setShowAlert(true);
    setTimeout(() => setShowAlert(false), 2200); // Display for 2.2 seconds
  };

  const incrementQuantity = () => {
    if (quantity < product.stock) {
      setQuantity(quantity + 1);
    }
  };

  const decrementQuantity = () => {
    if (quantity > 1) {
      setQuantity(quantity - 1);
    }
  };

  return (
    <div>
      {/* Bootstrap Success Alert - top centered, fixed */}
      {showAlert && (
        <div
          className="alert alert-success text-center shadow rounded"
          style={{
            position: "fixed",
            left: 0,
            right: 0,
            top: "70px",
            maxWidth: "400px",
            margin: "0 auto",
            zIndex: 2000,
          }}
          role="alert"
        >
          {alertMsg}
        </div>
      )}

      {/* Breadcrumbs */}
      <section className="py-3">
        <div className="container">
          <nav aria-label="breadcrumb">
            <ol className="breadcrumb mb-0">
              <li className="breadcrumb-item">
                <Link to="/" className="text-decoration-none">Home</Link>
              </li>
              <li className="breadcrumb-item">
                <Link to="/shop" className="text-decoration-none">Shop</Link>
              </li>
              <li className="breadcrumb-item" aria-current="page">
                {product.name}
              </li>
            </ol>
          </nav>
        </div>
      </section>

      {/* Product Details */}
      <section className="py-5">
        <div className="container">
          <div className="row">
            {/* Gallery */}
            <div className="col-lg-6 d-flex gallery-wrapper gap-2">
              <div className="thumbnails-column" style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                {product.images.map((image, index) => (
                  <img
                    key={index}
                    src={image}
                    alt={`${product.name} ${index + 1}`}
                    className={`thumbnail-img ${selectedImage === index ? "active" : ""}`}
                    onClick={() => setSelectedImage(index)}
                    style={{
                      border: selectedImage === index ? "2px solid #007bff" : "2px solid transparent",
                      borderRadius: "8px",
                      width: "72px",
                      height: "72px",
                      objectFit: "cover",
                      cursor: "pointer",
                      boxShadow: selectedImage === index ? "0 0 8px #007bff44" : "none",
                    }}
                  />
                ))}
              </div>
              <div className="main-image-container flex-grow-1" style={{ paddingLeft: "14px" }}>
                <img
                  src={product.images[selectedImage]}
                  alt={product.name}
                  className="main-product-img"
                  style={{
                    width: "100%",
                    height: "370px",
                    objectFit: "cover",
                    borderRadius: "14px",
                    boxShadow: "0 8px 32px -2px rgba(70,80,100,0.10)"
                  }}
                />
              </div>
            </div>
            {/* Product Info */}
            <div className="col-lg-6">
              <h1 className="script-font h2 mb-3">{product.name}</h1>
              {/* Rating */}
              <div className="d-flex align-items-center mb-3">
                <div className="me-2">
                  {[...Array(5)].map((_, i) => (
                    <i
                      key={i}
                      className={`fas fa-star ${i < Math.floor(product.rating) ? "text-warning" : "text-muted"}`}
                    ></i>
                  ))}
                </div>
                <span className="text-muted">({product.rating})</span>
              </div>
              {/* Price */}
              <div className="mb-3">
                {product.originalPrice && (
                  <span className="original-price me-2" style={{ textDecoration: "line-through", color: "#888" }}>
                    ${product.originalPrice.toFixed(2)}
                  </span>
                )}
                <span className="product-price h4" style={{ color: "#e63946", fontWeight: "bold" }}>
                  ${product.price.toFixed(2)}
                </span>
              </div>
              {/* Description */}
              <p className="text-muted mb-4">{product.description}</p>
              {/* Stock */}
              <p className="mb-3">
                <strong>Availability:</strong> {product.stock} in stock
              </p>
              {/* Quantity Selector */}
              <div className="d-flex align-items-center mb-4">
                <label className="me-3"><strong>Quantity:</strong></label>
                <div className="d-flex align-items-center border rounded">
                  <button
                    className="btn btn-outline-secondary border-0"
                    onClick={decrementQuantity}
                    disabled={quantity <= 1}
                  >
                    -
                  </button>
                  <input
                    type="number"
                    className="form-control text-center border-0"
                    value={quantity}
                    onChange={(e) =>
                      setQuantity(
                        Math.max(1, Math.min(product.stock, parseInt(e.target.value) || 1))
                      )
                    }
                    style={{ width: "60px" }}
                    min="1"
                    max={product.stock}
                  />
                  <button
                    className="btn btn-outline-secondary border-0"
                    onClick={incrementQuantity}
                    disabled={quantity >= product.stock}
                  >
                    +
                  </button>
                </div>
              </div>
              {/* Action Buttons */}
              <div className="d-flex gap-3 mb-4">
                <button
                  className="btn btn-primary-custom btn-lg px-5"
                  onClick={handleAddToCart}
                >
                  ADD TO CART
                </button>
                <button className="btn btn-outline-danger">
                  <i className="fas fa-heart"></i>
                </button>
              </div>
              {/* Category */}
              <p className="mb-3"><strong>Category:</strong> {product.category}</p>
              {/* Share */}
              <div className="d-flex align-items-center">
                <strong className="me-3">Share:</strong>
                <div className="social-icons">
                  <a href="#" className="text-decoration-none me-2">
                    <i className="fab fa-facebook-f"></i>
                  </a>
                  <a href="#" className="text-decoration-none me-2">
                    <i className="fab fa-twitter"></i>
                  </a>
                  <a href="#" className="text-decoration-none me-2">
                    <i className="fab fa-pinterest"></i>
                  </a>
                  <a href="#" className="text-decoration-none me-2">
                    <i className="fab fa-google-plus-g"></i>
                  </a>
                  <a href="#" className="text-decoration-none me-2">
                    <i className="fas fa-envelope"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
          {/* Product Tabs */}
          <div className="row mt-5">
            <div className="col-12">
              <ul className="nav nav-tabs" role="tablist">
                <li className="nav-item" role="presentation">
                  <button
                    className={`nav-link ${activeTab === "description" ? "active" : ""}`}
                    onClick={() => setActiveTab("description")}
                  >
                    DESCRIPTION
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className={`nav-link ${activeTab === "additional" ? "active" : ""}`}
                    onClick={() => setActiveTab("additional")}
                  >
                    ADDITIONAL INFORMATION
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className={`nav-link ${activeTab === "shipping" ? "active" : ""}`}
                    onClick={() => setActiveTab("shipping")}
                  >
                    SHIPPING & RETURN
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className={`nav-link ${activeTab === "reviews" ? "active" : ""}`}
                    onClick={() => setActiveTab("reviews")}
                  >
                    REVIEWS
                  </button>
                </li>
              </ul>
              <div className="tab-content p-4 border border-top-0">
                {activeTab === "description" && (
                  <div>
                    <h4>Product Description</h4>
                    <p className="text-muted">{product.description}</p>
                    <p className="text-muted">{product.additionalInfo}</p>
                    <ul className="text-muted">
                      <li>Made with premium ingredients</li>
                      <li>Fresh daily preparation</li>
                      <li>Perfect for any occasion</li>
                    </ul>
                  </div>
                )}
                {activeTab === "additional" && (
                  <div>
                    <h4>Additional Information</h4>
                    <p className="text-muted">{product.additionalInfo}</p>
                    <table className="table">
                      <tbody>
                        <tr>
                          <td><strong>Weight</strong></td>
                          <td>0.5 kg</td>
                        </tr>
                        <tr>
                          <td><strong>Dimensions</strong></td>
                          <td>10 x 10 x 5 cm</td>
                        </tr>
                        <tr>
                          <td><strong>Ingredients</strong></td>
                          <td>Flour, Sugar, Eggs, Butter, Vanilla</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                )}
                {activeTab === "shipping" && (
                  <div>
                    <h4>Shipping & Return Information</h4>
                    <p className="text-muted">{product.shippingInfo}</p>
                    <ul className="text-muted">
                      <li>Free shipping on orders over $50</li>
                      <li>Standard delivery: 2-3 business days</li>
                      <li>Express delivery: 1-2 business days</li>
                      <li>30-day return policy</li>
                    </ul>
                  </div>
                )}
                {activeTab === "reviews" && (
                  <div>
                    <h4>Customer Reviews</h4>
                    {product.reviews.length > 0 ? (
                      product.reviews.map((review) => (
                        <div key={review.id} className="border-bottom pb-3 mb-3">
                          <div className="d-flex align-items-center mb-2">
                            <strong className="me-3">{review.name}</strong>
                            <div>
                              {[...Array(5)].map((_, i) => (
                                <i
                                  key={i}
                                  className={`fas fa-star ${i < review.rating ? "text-warning" : "text-muted"}`}
                                ></i>
                              ))}
                            </div>
                          </div>
                          <p className="text-muted">{review.comment}</p>
                        </div>
                      ))
                    ) : (
                      <p className="text-muted">
                        No reviews yet. Be the first to review this product!
                      </p>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
          {/* Related Products */}
          <div className="row mt-5">
            <div className="col-12">
              <h3 className="script-font h2 mb-4 text-center">
                RELATED PRODUCTS
              </h3>
              <div className="row">
                {products
                  .filter((p) => p.id !== product.id)
                  .slice(0, 4)
                  .map((relatedProduct) => (
                    <div key={relatedProduct.id} className="col-lg-3 col-md-6 mb-4">
                      <div className="card product-card h-100">
                        <img
                          src={relatedProduct.mainImage}
                          className="card-img-top product-image"
                          alt={relatedProduct.name}
                        />
                        <div className="card-body text-center">
                          <h5 className="card-title product-title">
                            {relatedProduct.name}
                          </h5>
                          <p className="card-text product-price">
                            ${relatedProduct.price.toFixed(2)}
                          </p>
                          <Link
                            to={`/product/${relatedProduct.id}`}
                            className="btn btn-outline-primary btn-sm"
                          >
                            View Details
                          </Link>
                        </div>
                      </div>
                    </div>
                  ))}
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* Newsletter */}
      <Newsletter />
    </div>
  );
};

export default ProductDetail;
