// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import { Link } from "react-router-dom";

const Footer = () => (
  <footer className="footer">
    <div className="container-fluid">
      <div className="footer-main row justify-content-between align-items-start">
        <div className="footer-col col-lg-3 col-md-6 mb-4">
          <h4 className="footer-logo">CakeStore</h4>
          <p className="footer-text">
            Join us on a journey of taste and tradition at Cake Store.
          </p>
        </div>
        {/* Contact */}
        <div className="footer-col col-lg-3 col-md-6 mb-4">
          <h5 className="footer-title">Contact</h5>
          <div className="footer-text">
            <p>Cake Store Inc.</p>
            <p>Salinas, CA</p>
            <p>831-585-4398</p>
            <p>
              <span style={{ fontWeight: 500, color: "#222" }}>
                contact@cakestore.com
              </span>
            </p>
          </div>
        </div>
        {/* Links */}
        <div className="footer-col col-lg-3 col-md-6 mb-4">
          <h5 className="footer-title">Links</h5>
          <div>
            <Link to="/" className="footer-link">
              Home
            </Link>
            <Link to="/shop" className="footer-link">
              Shop
            </Link>
            <Link to="/about" className="footer-link">
              About us
            </Link>
            <Link to="/team" className="footer-link">
              Team
            </Link>
          </div>
        </div>
        {/* Social */}
        <div className="footer-col col-lg-3 col-md-6 mb-4">
          <h5 className="footer-title">Follow us</h5>
          <div className="footer-social-row">
            <a href="#" className="footer-link social">
              <i className="fab fa-facebook-f"></i>
            </a>
            <a href="#" className="footer-link social">
              <i className="fab fa-twitter"></i>
            </a>
            <a href="#" className="footer-link social">
              <i className="fab fa-youtube"></i>
            </a>
            <a href="#" className="footer-link social">
              <i className="fab fa-pinterest"></i>
            </a>
            <a href="#" className="footer-link social">
              <i className="fab fa-instagram"></i>
            </a>
          </div>
          <div className="footer-social-row">
            <a href="#" className="footer-link social">
              <i className="fab fa-instagram"></i>
            </a>
          </div>
        </div>
      </div>
      {/* Bottom Bar */}
      <div className="footer-bottom row justify-content-between align-items-center">
        <div className="col-md-6">
          <p className="footer-credit">
            © 2024 Cake Store HTML Developed by{" "}
            <span style={{ color: "#111" }}>Cake Store</span>
          </p>
        </div>
        <div className="col-md-6 d-flex align-items-center justify-content-end">
          <span className="footer-text-light me-2">We Accept:</span>
          <img
            src="Icons/visa.png"
            alt="Visa"
            className="me-2"
            style={{ height: "26px" }}
          />
          <img
            src="Icons/american-express.png"
            alt="American Express"
            className="me-2"
            style={{ height: "26px" }}
          />
          <img
            src="Icons/master-card.png"
            alt="MasterCard"
            className="me-2"
            style={{ height: "26px" }}
          />
        </div>
      </div>
    </div>
  </footer>
);

export default Footer;
